import { PresetPet } from './types';

export const PRESET_PETS: PresetPet[] = [
  {
    id: 'sandra_bengal',
    name: 'Sandra',
    species: 'Cat',
    breed: 'Bengal',
    gender: '♀️',
    age: 'Age 3',
    bio: 'Sandra can turn a quiet afternoon into a solo show and she always seems very committed to the role.',
    badgeId: 'FD-26-SANDRA',
    description: 'Drama Queen Bengal cat.',
    previewColor: '#F59E0B',
    defaultPersonality: 'curious',
    spriteSheetUrl: '/sprites/calico_cat.png',
    frameWidth: 64,
    frameHeight: 64,
    columns: 4,
    rows: 4,
    fps: 8,
    animations: {
      idle: [0, 1, 2, 3],
      walk: [4, 5, 6, 7],
      sit: [8, 9, 10, 11],
      sleep: [12, 13, 14, 15]
    }
  },
  {
    id: 'bruno_labrador',
    name: 'Bruno',
    species: 'Dog',
    breed: 'Labrador',
    gender: '♂️',
    age: '1 year old',
    bio: 'Energetic and friendly Labrador who loves afternoon naps and desktop fetch.',
    badgeId: 'FD-26-BRUNO',
    description: 'Energetic and friendly Labrador companion.',
    previewColor: '#D4A373',
    defaultPersonality: 'playful',
    spriteSheetUrl: '/sprites/shiba_inu.png',
    frameWidth: 64,
    frameHeight: 64,
    columns: 4,
    rows: 4,
    fps: 10,
    animations: {
      idle: [0, 1, 2, 3],
      walk: [4, 5, 6, 7],
      sit: [8, 9, 10, 11],
      sleep: [12, 13, 14, 15]
    }
  },
  {
    id: 'papi_cavalier',
    name: 'Grandpapa Papi',
    species: 'Dog',
    breed: 'Cavalier',
    gender: '♂️',
    age: 'Age 6',
    bio: 'The oldest resident around here. He spends every afternoon quietly keeping an eye on everyone.',
    badgeId: 'FD-26-O6C511',
    description: 'Wise and calm Cavalier companion.',
    previewColor: '#C68B59',
    defaultPersonality: 'calm',
    spriteSheetUrl: '/sprites/shiba_inu.png',
    frameWidth: 64,
    frameHeight: 64,
    columns: 4,
    rows: 4,
    fps: 8,
    animations: {
      idle: [0, 1, 2, 3],
      walk: [4, 5, 6, 7],
      sit: [8, 9, 10, 11],
      sleep: [12, 13, 14, 15]
    }
  },
  {
    id: 'luna_cat',
    name: 'Luna',
    species: 'Cat',
    breed: 'British Shorthair',
    gender: '♀️',
    age: 'Age 2',
    bio: 'Elegant golden shorthair kitty who loves cozy sunbeams and gentle stretches.',
    badgeId: 'FD-26-LUNA',
    description: 'Cozy golden shorthair cat.',
    previewColor: '#F59E0B',
    defaultPersonality: 'calm',
    spriteSheetUrl: '/sprites/calico_cat.png',
    frameWidth: 64,
    frameHeight: 64,
    columns: 4,
    rows: 4,
    fps: 8,
    animations: {
      idle: [0, 1, 2, 3],
      walk: [4, 5, 6, 7],
      sit: [8, 9, 10, 11],
      sleep: [12, 13, 14, 15]
    }
  },
  {
    id: 'barnaby_samoyed',
    name: 'Barnaby',
    species: 'Dog',
    breed: 'Samoyed',
    gender: '♂️',
    age: 'Age 3',
    bio: 'Fluffy white cloud puppy with endless smiles and fluffy paws.',
    badgeId: 'FD-26-BARNABY',
    description: 'Fluffy cloud puppy.',
    previewColor: '#EC4899',
    defaultPersonality: 'cheerful',
    spriteSheetUrl: '/sprites/shiba_inu.png',
    frameWidth: 64,
    frameHeight: 64,
    columns: 4,
    rows: 4,
    fps: 10,
    animations: {
      idle: [0, 1, 2, 3],
      walk: [4, 5, 6, 7],
      sit: [8, 9, 10, 11],
      sleep: [12, 13, 14, 15]
    }
  },
  {
    id: 'milo_corgi',
    name: 'Milo',
    species: 'Dog',
    breed: 'Corgi',
    gender: '♂️',
    age: '2 years old',
    bio: 'Short legs, big heart! Loves trotting around your screen.',
    badgeId: 'FD-26-MILO',
    description: 'Playful Corgi pup.',
    previewColor: '#8B5CF6',
    defaultPersonality: 'playful',
    spriteSheetUrl: '/sprites/shiba_inu.png',
    frameWidth: 64,
    frameHeight: 64,
    columns: 4,
    rows: 4,
    fps: 10,
    animations: {
      idle: [0, 1, 2, 3],
      walk: [4, 5, 6, 7],
      sit: [8, 9, 10, 11],
      sleep: [12, 13, 14, 15]
    }
  }
];
